### ISSUE TITLE
这个训练好的DQN应该如何实际应用

### ISSUE THREAD

**Issue by wuzxc1230123** [hibana2077/AI_Trader#1]

**Comment by hibana2077** [comment]
目前還在寫訓練的程式碼，以後預計整合到freqtrade或是其他交易框架

**Comment by wuzxc1230123** [comment]
我想写一个信号机器人，我想试试链接币安，用实时数据调用模型，这个应该怎么实现&nbsp;


j
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月4日(星期二) 上午10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hibana2077/AI_Trader] 这个训练好的DQN应该如何实际应用 (Issue #1)





 
目前還在寫訓練的程式碼，以後預計整合到freqtrade或是其他交易框架

**Comment by hibana2077** [comment]
可以用CCXT中的binance 搭配APScheduler 走 http request或是直接用websocket

**Comment by wuzxc1230123** [comment]
是直接加载模型，传入200条K线，然后获取最后一个action&nbsp;&nbsp;
还是重写env 获取实时数据
&nbsp;


j
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月4日(星期二) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hibana2077/AI_Trader] 这个训练好的DQN应该如何实际应用 (Issue #1)





 
可以用CCXT中的binance 搭配APScheduler 走 http request或是直接用websocket

**Comment by hibana2077** [comment]
兩種都可以

**Comment by wuzxc1230123** [comment]
第一种有参考的例子吗，我只是挺老大他们说过，想学习一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月4日(周二) 下午2:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hibana2077/AI_Trader] 这个训练好的DQN应该如何实际应用 (Issue #1)




 
兩種都可以

**Comment by hibana2077** [comment]
目前還沒寫好，寫完後會一併放上去

**Comment by wuzxc1230123** [comment]
到时候可以通知一下我吗，我很想学习这个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月5日(周三) 下午5:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hibana2077/AI_Trader] 这个训练好的DQN应该如何实际应用 (Issue #1)




 
目前還沒寫好，寫完後會一併放上去

**Comment by hibana2077** [comment]
你按下 fellow 和 star 的話，有更新就會收到通知
